deploy:
  provider: openshift
  user: jibinmathews7@gmail.com
  password:
    secure: OuAMu1sQcLG9J9G/pgGVUhmNwaHW1L5lcWE1aMux3J+Gj3FPz+5lzxwcEZRKisXNFy2b9d/nh8dPmUGAjk5c5yt1LnDNyTHFsPBogf1A7CKS2BwrNfzX0S77ckfBCaw0/tYPWdwZ7Ra7DnE35a1LfTB3Q8SJvopaL6kZmNFaFOBzm04NhUctns2VDB8myXpJi9LpPyDnDcM2OKbpu/bNsyK5kOh0irz5xU9gdYmefp2D17KOp5hDdqPQc/EEZF0zCybvmSMl1LeTAvM4v388Tici3qwe6LL2xNcPDe2swdt6vRshb44EZm1pzFDFgonJ7+bBgVuqgnAg5y8RqVlooVStpcXfWWeOYH6A0OcF+16f0ln6p3o5jgyEx6sWSxBR4v9/vc9Wld3qNXQMkG7xC7jXjejrZ0kMPIdzQJwvw7z6Ut9eGygpGLLTQMLALKVnfQtzOenApqmrFao/jXwH2swvGHo8G9twNWDm/tErqa50LPVUD7Y28cw1K6I7DuefzJY6SX4TezfxmrMEGbmepTr2KhNrciA601iqwrK9J4SPq3FQlWWwoyKhAP46mn5s2P7Mq2KL+mcLrKhQKSAZQV/04FRo8RFfn7F1Y9cTy4nqmG5wjaaXcToOV1UF5dFv0GKKhHh3jHmDKGWaMv9dNdmJPls3yylPvgCKuJJrIZc=
  app: foodkart
  domain: jazzyarchitect
  on: 
    repo: code-lucidal58/FoodKartServer
